config/routes.rb
Rails.application.routes.draw do
  resources :example do
    collection do
      get 'index'
      get 'asset_vanilla_js'
      get 'inline_vanilla_js'
      get 'remote_vanilla_js'
      get 'asset_vanilla_es6'
      get 'inline_vanilla_es6'
      get 'remote_vanilla_es6'
      get 'asset_vanilla_es6_js'
      get 'remote'
      get 'remote3'
    end
  end

  root 'example#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/es6_controller.rb
class Es6Controller < ApplicationController
  def index
  end

  def asset_vanilla_es6
  end

  def inline_vanilla_es6
  end

  def remote_vanilla_es6
  end

  def remote
  end
end

app/controllers/example_controller.rb
class ExampleController < ApplicationController
  def index
  end

  #.js
  def asset_vanilla_js
  end

  def inline_vanilla_js
  end

  def remote_vanilla_js
  end

  #.es6
  def asset_vanilla_es6
  end

  def inline_vanilla_es6
  end

  def remote_vanilla_es6
  end

  #.es6.js
  def asset_vanilla_es6_js
  end
  
  #remote scripts:
  def remote
  end

  def remote3
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/es6/remote_vanilla_es6.html.erb
<h1>Remote vanilla ES6</h1>
<h4>File: remote.js.es6</h4>

<%= link_to "Execute remote.js.es6", remote_es6_index_path, remote: true %>
<br/>
<br/>
<div id="remote-es6"></div>

app/views/example/asset_vanilla_es6.html.erb
<h1>Asset vanilla ES6</h1>
<h4>File: app/assets/javascripts/asset.es6</h4>

<%= link_to "Execute asset.es6", "#", id: "asset-es6-button" %>
<br/>
<br/>
<div id="asset-es6"></div>

app/views/example/asset_vanilla_es6_js.html.erb
<h1>Asset vanilla ES6.JS</h1>
<h4>File: app/assets/javascripts/asset.es6.js</h4>

<%= link_to "Execute asset.es6.js", "#", id: "asset-es6-js-button" %>
<br/>
<br/>
<div id="asset-es6-js"></div>

app/views/example/asset_vanilla_js.html.erb
<h1>Asset vanilla JS</h1>
<h4>File: app/assets/javascripts/asset.js</h4>

<%= link_to "Execute asset.js", "#", id: "asset-js-button" %>
<br/>
<br/>
<div id="asset-js"></div>

app/views/example/inline_vanilla_es6.html.erb
<h1>Inline vanilla ES6 with ERB</h1>
<h4>File: inline_vanilla_es6.html.erb</h4>
<div id="inline-es6"></div>

<script>
  <%= es6_transform do %>
    let interval,
        i= 0,
        element= document.getElementById("inline-es6");

    element.innerHTML= "Fibonacci sequence: "
    startFibonacci();
    console.log("Inline vanilla ES6 ready")

    function startFibonacci(limit=10){
      interval= setInterval(() => {
        element.innerHTML+= fibonacci(i++) + ", ";
        if (i>10) {stopFibonacci()};
      }, 1000);
    }

    function stopFibonacci(){
      clearInterval(interval);
      element.innerHTML+= " ...";
    }

    function fibonacci(n=0) {
       return n>1 ? fibonacci(n-1)+fibonacci(n-2) : n;
    }
  <% end %>
</script>

app/views/example/inline_vanilla_js.html.erb
<h1>Inline vanilla JS with ERB</h1>
<h4>File: inline_vanilla_js.html.erb</h4>
<div id="inline-js"></div>

<script>
    var interval,
        i= 0,
        element= document.getElementById("inline-js");

    element.innerHTML= "Fibonacci sequence on inline js: "
    startFibonacci();
    console.log("Inline vanilla .js ready")

    function startFibonacci(){
      interval= setInterval(function() {
        element.innerHTML+= fibonacci(i++) + ", ";
        if (i>10) {stopFibonacci()};
      }, 1000);
    }

    function stopFibonacci(){
      clearInterval(interval);
      element.innerHTML+= " ...";
    }

    function fibonacci(n=0) {
       return n>1 ? fibonacci(n-1)+fibonacci(n-2) : n;
    }
</script>

app/views/example/remote_vanilla_es6.html.erb
<h1>Remote vanilla ES6</h1>
<h4>File: remote.js.es6</h4>

<%= link_to "Execute remote.js.es6", remote_example_index_path, remote: true %>
<br/>
<br/>
<div id="remote-es6"></div>

app/views/example/remote_vanilla_es6_js.html.erb
<h1>Remote vanilla ES6.JS</h1>
<h4>File: remote2.es6.js</h4>

<%= link_to "Execute remote2.es6.js", remote2_example_index_path, remote: true %>
<br/>
<br/>
<div id="remote-es6-js"></div>

app/views/example/remote_vanilla_js.html.erb
<h1>Remote vanilla JS</h1>
<h4>File: remote3.js</h4>

<%= link_to "Execute remote3.js", remote3_example_index_path, remote: true %>
<br/>
<br/>
<div id="remote-js"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>es6-rails Example</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to "Asset Vanilla JS", asset_vanilla_js_example_index_path %> <br/>
<%= link_to "Inlne Vanilla JS", inline_vanilla_js_example_index_path %> <br/>
<%= link_to "Remote Vanilla JS", remote_vanilla_js_example_index_path %> <br/>

<br/>
<br/>

<%= link_to "Asset Vanilla ES6", asset_vanilla_es6_example_index_path %> <br/>
<%= link_to "Inlne Vanilla ES6", inline_vanilla_es6_example_index_path %> <br/>
<%= link_to "Remote Vanilla ES6", remote_vanilla_es6_example_index_path %> <br/>

<br/>
<br/>

<%= link_to "Asset Vanilla ES6.JS", asset_vanilla_es6_js_example_index_path %> <br/>

<br/>
<br/>

<hr/>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>Inline vanilla ES6 with ERB</h1>
<div id="inline-es6"></div>

<script>
  <%= es6_transform do %>
    let interval,
        i= 0,
        element= document.getElementById("inline-es6");

    element.innerHTML= "Fibonacci sequence: "
    startFibonacci();

    function startFibonacci(limit=10){
      interval= setInterval(() => {
        element.innerHTML+= fibonacci(i++) + ", ";
        if (i>10) {stopFibonacci()};
      }, 1000);
    }

    function stopFibonacci(){
      clearInterval(interval);
      element.innerHTML+= " ...";
    }

    function fibonacci(n=0) {
       return n>1 ? fibonacci(n-1)+fibonacci(n-2) : n;
    }
  <% end %>
</script>